FROM nvidia/opengl:1.1-glvnd-devel-ubuntu16.04

################################## JUPYTERLAB ##################################

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt-get update && apt-get install -yq --no-install-recommends \
	locales cmake git build-essential \
    python-pip python3-pip python3-setuptools \
    dirmngr gnupg2 lsb-release \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip setuptools \
 && python3 -m pip install jupyterlab bash_kernel \
 && python3 -m bash_kernel.install

ENV SHELL=/bin/bash \
	NB_USER=jovyan \
	NB_UID=1000 \
	LANG=en_US.UTF-8 \
	LANGUAGE=en_US.UTF-8

ENV HOME=/home/${NB_USER}

RUN adduser --disabled-password \
	--gecos "Default user" \
	--uid ${NB_UID} \
	${NB_USER}

EXPOSE 8888

CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0", "--NotebookApp.token=''"]

###################################### ROS #####################################

# setup keys
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# setup sources.list
RUN echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    python-rosdep python-rosinstall python-vcstools python-catkin-tools \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init

RUN rosdep fix-permissions

USER ${NB_USER}

RUN rosdep update

USER root

# install ros packages
ENV ROS_DISTRO kinetic
RUN apt-get update && apt-get install -y \
    ros-kinetic-desktop-full \
    && rm -rf /var/lib/apt/lists/*

# setup entrypoint
COPY ./ros_entrypoint.sh /
RUN chmod a+x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]

RUN mkdir -p /home/jovyan/.ros
RUN chown jovyan.jovyan /home/jovyan/.ros

##################################### TAIL #####################################

#RUN apt-get update && apt-get install -y \
#    ros-kinetic-turtlebot-gazebo \
#    && rm -rf /var/lib/apt/lists/*

RUN mkdir ${HOME}/ros-gazebo

RUN chown ${NB_UID} ${HOME}/ros-gazebo
 
USER ${NB_USER}

WORKDIR ${HOME}/ros-gazebo

RUN mkdir ${HOME}/ros-gazebo/catkin_ws/

ADD src ${HOME}/ros-gazebo/catkin_ws/src

RUN rosdep update && \
    rosdep install -y \
      --from-paths \
        ${HOME}/ros-gazebo/catkin_ws/src/ \
      --ignore-src && \
    rm -rf /var/lib/apt/lists/*

RUN cd ${HOME}/ros-gazebo/catkin_ws \
 && catkin config --extend /opt/ros/$ROS_DISTRO \
 && catkin build


